export const collegesData = [
  {
    rank: 1,
    college: "IIT Madras - Indian Institute of Technology",
    location: "Chennai, Tamil Nadu",
    approval: "AICTE Approved",
    course: "B.Tech Artificial Intelligence",
    exam_cutoff: "JEE-Advanced 2024 Cutoff: 419",
    course_fees: "₹2,42,000",
    placement: {
      average_package: "₹21,48,000",
      highest_package: "₹1,98,00,000",
    },
    user_reviews: {
      rating: 4.3,
      based_on: "382 User Reviews",
      highlight: "Best in Social Life",
    },
    ranking: "#03/745 in India 2025",
  },
  {
    rank: 2,
    college: "IIT Delhi - Indian Institute of Technology",
    location: "New Delhi, Delhi NCR",
    approval: "",
    course: "B.Tech - M.Tech Mathematics and Computing",
    exam_cutoff: "JEE-Advanced 2024 Cutoff: 417",
    course_fees: "₹2,28,650",
    placement: {
      average_package: "₹25,82,000",
      highest_package: "₹2,00,00,000",
    },
    user_reviews: {
      rating: 4.3,
      based_on: "589 User Reviews",
      highlight: "Best in Social Life",
    },
    ranking: "#02/745 in India 2025",
  },
  {
    rank: 3,
    college: "IIT Bombay - Indian Institute of Technology",
    location: "Mumbai, Maharashtra",
    approval: "AICTE, UGC Approved",
    course: "B.Tech Computer Science Engineering",
    exam_cutoff: "JEE-Advanced 2024 Cutoff: 68",
    course_fees: "₹2,30,700",
    placement: {
      average_package: "₹23,50,000",
      highest_package: "₹3,67,00,000",
    },
    user_reviews: {
      rating: 4.4,
      based_on: "355 User Reviews",
      highlight: "",
    },
    ranking: "#01/745 in India 2025",
  },
  {
    rank: 4,
    college: "IIT Kanpur - Indian Institute of Technology",
    location: "Kanpur, Uttar Pradesh",
    approval: "AICTE Approved",
    course: "B.Tech Electrical Engineering",
    exam_cutoff: "JEE-Advanced 2024 Cutoff: 200",
    course_fees: "₹2,35,000",
    placement: {
      average_package: "₹18,20,000",
      highest_package: "₹1,50,00,000",
    },
    user_reviews: {
      rating: 4.5,
      based_on: "270 User Reviews",
      highlight: "Best for Research",
    },
    ranking: "#05/745 in India 2025",
  },
  {
    rank: 5,
    college: "IIT Kharagpur - Indian Institute of Technology",
    location: "Kharagpur, West Bengal",
    approval: "AICTE Approved",
    course: "B.Tech Mechanical Engineering",
    exam_cutoff: "JEE-Advanced 2024 Cutoff: 300",
    course_fees: "₹2,40,000",
    placement: {
      average_package: "₹20,00,000",
      highest_package: "₹1,75,00,000",
    },
    user_reviews: {
      rating: 4.6,
      based_on: "400 User Reviews",
      highlight: "Best Campus Life",
    },
    ranking: "#04/745 in India 2025",
  },
  {
    rank: 6,
    college: "NIT Trichy - National Institute of Technology",
    location: "Tiruchirappalli, Tamil Nadu",
    approval: "UGC Approved",
    course: "B.Tech Civil Engineering",
    exam_cutoff: "JEE-Main 2024 Cutoff: 4500",
    course_fees: "₹1,50,000",
    placement: {
      average_package: "₹12,00,000",
      highest_package: "₹75,00,000",
    },
    user_reviews: {
      rating: 4.2,
      based_on: "600 User Reviews",
      highlight: "Great Alumni Network",
    },
    ranking: "#10/745 in India 2025",
  },
  {
    rank: 7,
    college: "BITS Pilani - Birla Institute of Technology and Science",
    location: "Pilani, Rajasthan",
    approval: "Deemed University",
    course: "B.Tech Electronics and Communication",
    exam_cutoff: "BITSAT 2024 Cutoff: 370",
    course_fees: "₹4,00,000",
    placement: {
      average_package: "₹15,00,000",
      highest_package: "₹2,10,00,000",
    },
    user_reviews: {
      rating: 4.4,
      based_on: "500 User Reviews",
      highlight: "Excellent Placements",
    },
    ranking: "#06/745 in India 2025",
  },
  {
    rank: 8,
    college: "VIT Vellore - Vellore Institute of Technology",
    location: "Vellore, Tamil Nadu",
    approval: "NAAC A++",
    course: "B.Tech Biotechnology",
    exam_cutoff: "VITEEE 2024 Cutoff: 25000",
    course_fees: "₹2,80,000",
    placement: {
      average_package: "₹7,50,000",
      highest_package: "₹44,00,000",
    },
    user_reviews: {
      rating: 4.1,
      based_on: "700 User Reviews",
      highlight: "Best Infrastructure",
    },
    ranking: "#20/745 in India 2025",
  },
  {
    rank: 9,
    college: "SRM University",
    location: "Chennai, Tamil Nadu",
    approval: "NAAC A++",
    course: "B.Tech Information Technology",
    exam_cutoff: "SRMJEEE 2024 Cutoff: 32000",
    course_fees: "₹3,00,000",
    placement: {
      average_package: "₹6,80,000",
      highest_package: "₹50,00,000",
    },
    user_reviews: {
      rating: 3.9,
      based_on: "800 User Reviews",
      highlight: "Innovative Curriculum",
    },
    ranking: "#25/745 in India 2025",
  },
  {
    rank: 10,
    college: "Amity University",
    location: "Noida, Uttar Pradesh",
    approval: "UGC Approved",
    course: "B.Tech Computer Science",
    exam_cutoff: "Direct Admission",
    course_fees: "₹3,50,000",
    placement: {
      average_package: "₹5,50,000",
      highest_package: "₹30,00,000",
    },
    user_reviews: {
      rating: 3.8,
      based_on: "1000 User Reviews",
      highlight: "Diverse Campus",
    },
    ranking: "#50/745 in India 2025",
  },
  {
    rank: 11,
    college:
      "IIIT Hyderabad - International Institute of Information Technology, Hyderabad",
    location: "Hyderabad, Telangana",
    approval: "UGC Approved",
    course: "B.Tech Computer Science and Engineering",
    exam_cutoff: "JEE Advanced",
    course_fees: "₹3,00,000",
    placement: {
      average_package: "₹20,00,000",
      highest_package: "₹1,50,00,000",
    },
    user_reviews: {
      rating: 4.6,
      based_on: "450 User Reviews",
      highlight: "Top-tier placements and infrastructure",
    },
    ranking: "#99 in India 2025",
  },
  {
    rank: 12,
    college: "IIT Guwahati - Indian Institute of Technology, Guwahati",
    location: "Guwahati, Assam",
    approval: "UGC Approved",
    course: "B.Tech Electrical Engineering",
    exam_cutoff: "JEE Advanced",
    course_fees: "₹2,00,000",
    placement: {
      average_package: "₹15,00,000",
      highest_package: "₹80,00,000",
    },
    user_reviews: {
      rating: 4.3,
      based_on: "310 User Reviews",
      highlight: "Strong research opportunities",
    },
    ranking: "#25 in India 2025",
  },
  {
    rank: 13,
    college:
      "SRM University - SRM Institute of Science and Technology, Chennai",
    location: "Chennai, Tamil Nadu",
    approval: "UGC Approved",
    course: "B.Tech Biotechnology",
    exam_cutoff: "Direct Admission",
    course_fees: "₹2,60,000",
    placement: {
      average_package: "₹7,50,000",
      highest_package: "₹35,00,000",
    },
    user_reviews: {
      rating: 4.0,
      based_on: "200 User Reviews",
      highlight: "Research and innovation-driven curriculum",
    },
    ranking: "#35 in India 2025",
  },
  {
    rank: 14,
    college: "Manipal Institute of Technology, Manipal",
    location: "Manipal, Karnataka",
    approval: "UGC Approved",
    course: "B.Tech Aeronautical Engineering",
    exam_cutoff: "JEE Mains",
    course_fees: "₹3,20,000",
    placement: {
      average_package: "₹8,20,000",
      highest_package: "₹40,00,000",
    },
    user_reviews: {
      rating: 4.2,
      based_on: "370 User Reviews",
      highlight: "World-class infrastructure and faculty",
    },
    ranking: "#33 in India 2025",
  },
  {
    rank: 15,
    college: "Amrita Vishwa Vidyapeetham, Coimbatore",
    location: "Coimbatore, Tamil Nadu",
    approval: "UGC Approved",
    course: "B.Tech Cybersecurity",
    exam_cutoff: "JEE Mains",
    course_fees: "₹2,40,000",
    placement: {
      average_package: "₹9,50,000",
      highest_package: "₹42,00,000",
    },
    user_reviews: {
      rating: 4.1,
      based_on: "280 User Reviews",
      highlight: "Strong industry connections and placements",
    },
    ranking: "#23 in India 2025",
  },
];
